[package]
name = "fastlog"
version = "0.1.0"
edition = "2021"
description = "Fastest logging library 🪵."
license = "Apache"
repository = "https://github.com/WANG-lp/fastlog"

[dependencies]
chrono = "0.4"
core_affinity = "0.8"
log = { version = "0.4", features = ["std"] }
crossbeam-channel = "0.5"
lockfree = "0.5.1"
once_cell = "1"
fastrand = "2"
ufmt = "0.2"
symlink = "0.1.0"
libc = "*"

[profile.release-opt]
inherits = "release"
opt-level = "z"

[[bin]]
name = "bench_it"
path = "src/bench_it.rs"
