[package]
name = "bench"
version = "0.1.0"
edition = "2021"

[dependencies]
fastlog = { path = "../", features = ["level-info"] }
spdlog-rs = { version = "0.3", features = ["level-info", "multi-thread", "flexible-string", "source-location"] }
quanta = "0.12"
fastrand = "2"
once_cell = "1"